import { m, useScroll, useTransform } from "framer-motion";
import { useRef } from "react";
import { Link } from "react-router-dom";

// Plain facts, not counters. The figures that used to animate here — years,
// portfolio value, a satisfaction percentage — were not sourced from anything.
const facts = [
  { value: "Gurgaon & Delhi", label: "Where we work" },
  { value: "Buying & selling", label: "Both sides of the deal" },
  { value: "Since 2010", label: "In this market" },
];

export function HeroSection() {
  const ref = useRef<HTMLElement>(null);
  const { scrollYProgress } = useScroll({
    target: ref,
    offset: ["start start", "end start"],
  });

  const bgY = useTransform(scrollYProgress, [0, 1], ["0%", "30%"]);
  const contentY = useTransform(scrollYProgress, [0, 1], ["0%", "15%"]);
  const contentOpacity = useTransform(scrollYProgress, [0, 0.6], [1, 0]);
  // The block fades to opacity 0 but stays in the DOM, so both CTAs remained
  // focusable while completely invisible — a keyboard user tabbed onto nothing
  // they could see (WCAG 2.4.7). Drive visibility from the same value so the
  // browser removes them from the tab order once they're gone.
  const contentVisibility = useTransform(scrollYProgress, (v) =>
    v > 0.58 ? "hidden" : "visible",
  );

  return (
    <section ref={ref} className="relative min-h-screen flex items-center justify-center overflow-hidden">
      <m.div className="absolute inset-0" style={{ y: bgY }}>
        {/* Served from public/ rather than imported: the prerendered HTML needs a
            stable path it can name, and Vite hashes anything imported from src/.
            AVIF first, WebP next, JPEG last. A phone at 2x picks the 828w AVIF —
            36 kB against the 373 kB JPEG this replaced. Variants are generated by
            scripts/optimize-images.py and committed. */}
        <picture>
          {/* Narrow screens get a purpose-made 3:4 crop, not a sliver of the
              panorama: object-cover on a 2.54:1 source in a phone-shaped box
              discards ~82% of the width. Media-query sources must come first —
              the browser takes the first one that matches. */}
          <source
            media="(max-width: 767px)"
            type="image/avif"
            srcSet="/img/hero-bg-mobile-480.avif 480w, /img/hero-bg-mobile-750.avif 750w"
            sizes="100vw"
          />
          <source
            media="(max-width: 767px)"
            type="image/webp"
            srcSet="/img/hero-bg-mobile-480.webp 480w, /img/hero-bg-mobile-750.webp 750w"
            sizes="100vw"
          />
          <source
            type="image/avif"
            srcSet="/img/hero-bg-640.avif 640w, /img/hero-bg-828.avif 828w, /img/hero-bg-1280.avif 1280w, /img/hero-bg-1893.avif 1893w"
            sizes="100vw"
          />
          <source
            type="image/webp"
            srcSet="/img/hero-bg-640.webp 640w, /img/hero-bg-828.webp 828w, /img/hero-bg-1280.webp 1280w, /img/hero-bg-1893.webp 1893w"
            sizes="100vw"
          />
          <img
            src="/img/hero-bg-1893.jpg"
            alt="Apartment balconies overlooking a golf course and low-density villas"
            width={1893}
            height={744}
            className="w-full h-[120%] object-cover"
            loading="eager"
            decoding="async"
            // React 18 doesn't recognise camelCase fetchPriority; the lowercase
            // DOM attribute is what the browser reads.
            {...{ fetchpriority: "high" }}
          />
        </picture>
        {/* Two scrims, not one. The base keeps the photo visible; the second
            darkens only where the copy sits, so contrast is a property of the
            layout rather than of whichever photograph is behind it. Measured:
            white reaches 8.5:1 and gold-light 4.4:1 in the text band, while the
            right of the frame keeps the base alone and stays legible as an image. */}
        <div className="absolute inset-0 bg-gradient-to-b from-secondary/65 via-secondary/45 to-secondary/80" />
        <div className="absolute inset-0 bg-secondary/45 md:bg-transparent" />
        <div className="absolute inset-0 hidden md:block bg-gradient-to-r from-secondary/85 via-secondary/60 to-transparent" />
      </m.div>

      <m.div
        className="relative z-10 max-w-7xl mx-auto px-6 pt-32 pb-20 w-full"
        style={{ y: contentY, opacity: contentOpacity, visibility: contentVisibility }}
      >
        <div className="max-w-3xl">
          <m.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="text-secondary-foreground text-sm font-semibold tracking-[0.3em] uppercase mb-6"
          >
            Real Estate Agency · Gurgaon &amp; Delhi NCR
          </m.p>

          <m.h1
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.4 }}
            className="font-heading text-4xl md:text-6xl lg:text-7xl font-bold leading-[0.95] tracking-tight text-secondary-foreground mb-6"
          >
            Buy well in Gurgaon.
            <br />
            Sell for what it&rsquo;s <span className="text-gold-light">actually worth.</span>
          </m.h1>

          <m.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.6 }}
            className="text-lg md:text-xl text-secondary-foreground/70 max-w-xl mb-10 font-light leading-relaxed"
          >
            A full-service agency for Gurgaon and Delhi, partnered with the premium
            builders — and on your side of the table whichever side you are on.
          </m.p>

          {/* Stats */}
          <m.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.7 }}
            className="flex flex-wrap gap-8 mb-10"
          >
            {facts.map((fact) => (
              <div key={fact.label}>
                <p className="font-heading text-2xl md:text-3xl font-bold text-gold-light">
                  {fact.value}
                </p>
                <p className="text-secondary-foreground/60 text-xs mt-1 tracking-wider uppercase">{fact.label}</p>
              </div>
            ))}
          </m.div>

          {/* CTAs */}
          <m.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.9 }}
            className="flex flex-col sm:flex-row gap-4"
          >
            {/* Two doors, matching the two halves of the headline. The visitor
                declares intent rather than being asked to book our calendar —
                which is what a business working both sides of the deal needs. */}
            <Link
              to="/properties"
              className="bg-primary text-primary-foreground px-8 py-4 rounded-lg text-base font-semibold hover:bg-gold-light transition-colors text-center"
            >
              I want to buy
            </Link>
            <Link
              to="/sell"
              className="border-2 border-primary text-primary px-8 py-4 rounded-lg text-base font-semibold hover:bg-primary hover:text-primary-foreground transition-colors text-center"
            >
              I want to sell
            </Link>
          </m.div>
        </div>
      </m.div>
    </section>
  );
}
